{{- if .Values.rabbitmq.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "celery-chart.fullname" . }}-rabbitmq-config
  namespace: ingress-nginx
  labels:
    {{- include "celery-chart.rabbitmqLabels" . | nindent 4 }}
data:
  rabbitmq.conf: |
    ## Clustering
    cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
    cluster_formation.classic_config.nodes.1 = rabbit@{{ include "celery-chart.fullname" . }}-rabbitmq
    
    ## Management
    management.tcp.port = 15672
    management.tcp.ip = 0.0.0.0
    
    ## Default user
    default_user = {{ .Values.rabbitmq.auth.username }}
    default_pass = {{ .Values.rabbitmq.auth.username }}
    
    ## Logging
    log.console = true
    log.console.level = info
    
    ## Memory
    vm_memory_high_watermark.relative = 0.6
    
    ## Disk
    disk_free_limit.relative = 1.0
{{- end }}
