# 이름 오버라이드 설정
fullnameOverride: "api"

image:
  repository: kc-sfacspace.kr-central-2.kcr.dev/team2-repo/scratcha-backend
  tag: "20250909070255-6eded3d5b24206853521593c2cae9b204a6ccfb6"
  pullPolicy: IfNotPresent
deployment:
  maxUnavailable: 0
  maxSurge: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 8001
configMapName: app-config
profile: "local"

# HPA 설정
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  #메모리 제한 설정
  memoryLimit: "4Gi"
  memoryRequest: "2Gi"
  cpuLimit: "3000m"
  cpuRequest: "1500m"