# 이름 오버라이드 설정
fullnameOverride: "api"

image:
  repository: kc-sfacspace.kr-central-2.kcr.dev/team2-repo/scratcha-backend
  tag: "20250915064754-b4020a00ce4b2dd130fccbf6dabbd1590f280f63"

  pullPolicy: IfNotPresent
deployment:
  maxUnavailable: 0
  maxSurge: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 8001
profile: "local"

# RabbitMQ 연결 설정 (celery-chart에서 배포된 RabbitMQ 참조)
rabbitmq:
  enabled: true
  host: "celery-chart-rabbitmq"  # 같은 네임스페이스(ingress-nginx)에서 간단하게 참조
  port: "5672"
  username: "admin"
  vhost: "/"
  # 비밀번호는 Secret에서 참조
  existingSecret: "backend-rabbitmq"
  existingSecretPasswordKey: "RABBITMQ_PASSWORD"

# HPA 설정
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  #메모리 제한 설정
  memoryLimit: "1500Mi"
  memoryRequest: "1000Mi"
  cpuLimit: "1000m"
  cpuRequest: "500m"