# 이름 오버라이드 설정
fullnameOverride: "api"

image:
  repository: kc-sfacspace.kr-central-2.kcr.dev/team2-repo/scratcha-backend
  tag: "20250916065606-b92e950c681dd7a1d8339b9182e5709bb3180f37"

  pullPolicy: IfNotPresent
deployment:
  maxUnavailable: 0
  maxSurge: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 8001
  metricsPort: 8000
  metricsTargetPort: 8000
profile: "local"

# HPA 설정
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 9
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  #메모리 제한 설정
  memoryLimit: "2000Mi"
  memoryRequest: "1500Mi"
  cpuLimit: "1000m"
  cpuRequest: "500m"

# Prometheus 모니터링 설정
monitoring:
  enabled: true
  namespace: "monitoring"

# RabbitMQ 설정
rabbitmq:
  enabled: true
