# 이름 오버라이드 설정
fullnameOverride: "api"

image:
  repository: kc-sfacspace.kr-central-2.kcr.dev/team2-repo/scratcha-backend
  tag: "20250903023308-8fe7982beeadc87701df82a9dd3ce3784e7e17a9"
  pullPolicy: IfNotPresent
deployment:
  maxUnavailable: 0
  maxSurge: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 8001
configMapName: app-config
profile: "local"

# HPA 설정
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  #메모리 제한 설정
  memoryLimit: "1Gi"
  memoryRequest: "500m"
  cpuLimit: "1000m"
  cpuRequest: "500m"