# 이름 오버라이드 설정
fullnameOverride: "api"

image:
  repository: kc-sfacspace.kr-central-2.kcr.dev/team2-repo/scratcha-backend
  tag: "20250910005753-f95ee8b8abd6eb476dbbbabd6f1970607ec7c258"

  pullPolicy: IfNotPresent
deployment:
  maxUnavailable: 0
  maxSurge: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 8001
profile: "local"

# HPA 설정
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  #메모리 제한 설정
  memoryLimit: "1500Mi"
  memoryRequest: "1000Mi"
  cpuLimit: "1000m"
  cpuRequest: "500m"