apiVersion: v2
name: monitoring-chart
description: A comprehensive monitoring stack with Prometheus, Grafana, Loki, and AlertManager
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "7.0.17"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: loki
    version: "5.36.3"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
  - name: alertmanager
    version: "0.24.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: alertmanager.enabled
