apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-chart.fullname" . }}-deployment
  namespace: ingress-nginx
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
      maxSurge: {{ .Values.deployment.maxSurge }}
  selector:
    matchLabels:
      {{- include "api-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api-chart.selectorLabels" . | nindent 8 }}
        app: fastapi-app
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "8001"
      annotations:
    spec:
      terminationGracePeriodSeconds: 20
      nodeSelector:
        kakaoi.io/kke-nodepool: team2-api
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PROFILE
          value: "{{ .Values.profile }}"
        - name: TZ
          value: "Asia/Seoul"
        {{- if .Values.rabbitmq.enabled }}
        - name: RABBITMQ_HOST
          valueFrom:
            secretKeyRef:
              name: backend-rabbitmq
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            secretKeyRef:
              name: backend-rabbitmq
              key: RABBITMQ_PORT
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: backend-rabbitmq
              key: RABBITMQ_USER
        - name: RABBITMQ_VHOST
          valueFrom:
            secretKeyRef:
              name: backend-rabbitmq
              key: RABBITMQ_VHOST
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-rabbitmq
              key: RABBITMQ_PASSWORD
        {{- end }}
        envFrom:
        - secretRef:
            name: mysql-primary-secret
        - secretRef:
            name: mysql-secondary-secret
        - secretRef:
            name: jwt-secret
        - secretRef:
            name: mysql-url-secret
        - secretRef:
            name: backend-s3-url
        - secretRef:
            name: db-secret
        - secretRef:
            name: backend-rabbitmq
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "15"]
        {{- if .Values.autoscaling.enabled }}
        resources:
          requests:
            memory: {{ .Values.autoscaling.memoryRequest }}
            cpu: {{ .Values.autoscaling.cpuRequest }}
          limits:
            memory: {{ .Values.autoscaling.memoryLimit }}
            cpu: {{ .Values.autoscaling.cpuLimit }}
        {{- end }}
      imagePullSecrets:
      - name: kc-cr-secret