apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-chart.fullname" . }}-service
  namespace: ingress-nginx
  labels:
    {{- include "api-chart.labels" . | nindent 4 }}
    app: fastapi-app
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "api-chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
    - name: http-metrics
      port: {{ .Values.service.metricsPort | default 8000 }}
      targetPort: {{ .Values.service.metricsTargetPort | default 8000 }}