# 공통 이미지 설정 (api-chart와 동일)
image:
  repository: kc-sfacspace.kr-central-2.kcr.dev/team2-repo/scratcha-backend
  tag: "20250915084605-33b781bedb07b450eee424a4abd9de05dd261d95"
  pullPolicy: IfNotPresent

rabbitmq:
  enabled: true
  auth:
    username: "celery"
    existingSecret: "rabbitmq-secret"
    existingSecretPasswordKey: "RABBITMQ_PASSWORD"
  extraConfiguration: |
    loopback_users.guest = none
  service:
    type: ClusterIP
    ports:
      amqp: 5672
      management: 15672
  persistence:
    enabled: true
    size: 8Gi
    storageClass: csi-cinder-sc-retain               
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  nodeSelector:
    kakaoi.io/kke-nodepool: team2-api
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0

# Celery Worker 설정
worker:
  enabled: true
  replicas: 2
  env:
    profile: "production"
    timezone: "Asia/Seoul"
    # RabbitMQ 연결 설정
    CELERY_BROKER_URL: "amqp://celery:${RABBITMQ_PASSWORD}@rabbitmq-celery-chart-rabbitmq:5672//"
    CELERY_RESULT_BACKEND: "rpc://"
  envFrom:
    - secretRef:
        name: mysql-primary-secret
    - secretRef:
        name: mysql-secondary-secret
    - secretRef:
        name: jwt-secret
    - secretRef:
        name: mysql-url-secret
    - secretRef:
        name: backend-s3-url
    - secretRef:
        name: db-secret
    - secretRef:
        name: backend-rabbitmq
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  nodeSelector:
    kakaoi.io/kke-nodepool: team2-api
  imagePullSecrets:
    - name: kc-cr-secret

# Celery Beat 설정
beat:
  enabled: true
  env:
    profile: "production"
    timezone: "Asia/Seoul"
    # RabbitMQ 연결 설정
    CELERY_BROKER_URL: "amqp://celery:${RABBITMQ_PASSWORD}@rabbitmq-celery-chart-rabbitmq:5672//"
    CELERY_RESULT_BACKEND: "rpc://"
  envFrom:
    - secretRef:
        name: mysql-primary-secret
    - secretRef:
        name: mysql-secondary-secret
    - secretRef:
        name: jwt-secret
    - secretRef:
        name: mysql-url-secret
    - secretRef:
        name: backend-s3-url
    - secretRef:
        name: db-secret
    - secretRef:
        name: backend-secret
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"
  nodeSelector:
    kakaoi.io/kke-nodepool: team2-api
  imagePullSecrets:
    - name: kc-cr-secret