# RabbitMQ 차트 기본 설정
fullnameOverride: "rabbitmq"

# RabbitMQ 설정
rabbitmq:
  enabled: true
  # Bitnami RabbitMQ 차트 설정
  auth:
    username: "scratcha"
    # password는 Secret에서 참조
    existingSecret: "backend-rabbitmq"
    existingSecretPasswordKey: "RABBITMQ_PASSWORD"
  service:
    type: ClusterIP
    ports:
      amqp: 5672
      management: 15672
  # PersistentVolume 비활성화 (메모리 기반)
  persistence:
    enabled: false
  # 리소스 설정
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  # 노드 셀렉터
  nodeSelector:
    kakaoi.io/kke-nodepool: team2-api
