rabbitmq:
  enabled: true
  auth:
    username: "scratcha"
    existingSecret: "backend-rabbitmq"
    existingSecretPasswordKey: "RABBITMQ_PASSWORD"
  service:
    type: ClusterIP
    ports:
      amqp: 5672
      management: 15672
  persistence:
    enabled: true
    size: 8Gi
    storageClass: csi-cinder-sc-retain               
    accessModes:
      - ReadWriteOnce
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  nodeSelector:
    kakaoi.io/kke-nodepool: team2-api