replicaCount: 3

# 이름 오버라이드 설정
fullnameOverride: "front"

image:
  repository: kc-sfacspace.kr-central-2.kcr.dev/team2-repo/scratcha-frontend
  tag: "20250909075324-2f2091fd03a5ab4b996ef77bb52fd588336fb185"
  pullPolicy: IfNotPresent
deployment:
  maxUnavailable: 0
  maxSurge: 1
service:
  type: ClusterIP
  port: 80
configMapName: front-config
profile: "local"

# HPA 설정
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 7  # 더 많은 레플리카 허용
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  # 네트워크 트래픽 기반 메트릭 추가
  targetRequestsPerSecond: "50"  # 파드당 초당 요청 수
  targetConcurrentConnections: "100"  # 파드당 동시 연결 수
  #메모리 제한 설정
  memoryLimit: "1Gi"  # 프론트엔드는 메모리를 적게 사용
  memoryRequest: "512Mi"
  cpuLimit: "500m"
  cpuRequest: "250m"
