replicaCount: 3

# 이름 오버라이드 설정
fullnameOverride: "front"

image:
  repository: kc-sfacspace.kr-central-2.kcr.dev/team2-repo/scratcha-frontend
  tag: "20250916060608-fbfde203c7881b3988d4d9ece2d7fba3be5d56bc"
  pullPolicy: IfNotPresent
deployment:
  maxUnavailable: 0
  maxSurge: 1
service:
  type: ClusterIP
  port: 80
configMapName: front-config
profile: "local"

# HPA 설정
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 

  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  # 네트워크 트래픽 기반 메트릭 추가
  targetRequestsPerSecond: "50"  # 파드당 초당 요청 수
  targetConcurrentConnections: "100"  # 파드당 동시 연결 수
  #메모리 제한 설정
  memoryLimit: "1Gi"
  memoryRequest: "512Mi"
  cpuLimit: "500m"
  cpuRequest: "250m"
